apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jyi5iyc4u-java-quarkus
  janus-idp.io/tekton: jyi5iyc4u-java-quarkus
  backstage.io/kubernetes-id: jyi5iyc4u-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jyi5iyc4u-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
